# This file defines the contenttypes on the website. See the documentation for
# details: https://docs.bolt.cm/contenttypes/intro

homepage:
    name: Homepage
    singular_name: Homepage
    fields:
        title:
            type: text
            group: content
        payoff:
            type: text
            group: content
        image:
            type: image
            placeholder: https://source.unsplash.com/1920x640/?cityscape,landscape,nature/__random__
        slug:
            type: slug
            uses: title
            group: meta
    viewless: true
    singleton: true
    default_status: published
    icon_many: "fa:home"
    icon_one: "fa:home"

pages:
    name: Seiten
    singular_name: Seite
    fields:
        title:
            type: text
            group: content
        slug:
            type: slug
            uses: title
        teaser:
            type: html
            height: 150px
        body:
            type: html
            height: 300px
        showcontact:
            label: '"Interesse geweckt" anzeigen?' 
            type: checkbox

    taxonomy: [ groups, navigations ]
    recordsperpage: 20

persons:
    name: Personen
    singular_name: Person
    fields:
        name:
            type: text
            group: content
        slug:
            type: slug
            uses: name
        email:
            type: text
            group: content
        body:
            type: html
            height: 300px
        image:
            type: image
            group: media
            placeholder: https://via.placeholder.com/150x200/0000FF/808080
    relations:
    taxonomy: [ groups ]
    record_template: entry.twig
    listing_template: listing.twig
    listing_records: 10
    default_status: published
    sort: -datepublish
    recordsperpage: 20
